- name: Copy hosts file from template
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: check if host already registered
  command: subscription-manager list --available --match-installed --matches=*Satellite* --pool-only
  register: subs_result
  failed_when: false
  changed_when: "'This system is not yet registered' in subs_result.stderr"

- name: Register hosts using username
  command: subscription-manager register --username={{ rhn_username }} --password={{ rhn_password }}
  retries: 5
  delay: 5
  when: (subscription_use_username == "True" and subs_result.changed)

- name: Register hosts using activation key
  command: subscription-manager register --org={{ sub_mgr_org_id }} --activationkey={{ sub_mgr_activation_key }}
  retries: 5
  delay: 5
  when: subscription_use_username == False and subs_result.changed

- name: Check Red Hat subscription using username
  redhat_subscription:
    state: present
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
    pool: "{{ rhn_pool }}"
    #force_register: yes
  register: subscribe
  retries: 5
  delay: 5
  when: subscription_use_username == "True"

- name: Check Red Hat subscription using activation key
  redhat_subscription:
    state: present
    activationkey: "{{ sub_mgr_activation_key }}"
    org_id: "{{ sub_mgr_org_id }}"
    pool: "{{ rhn_pool }}"
    #force_register: yes
  register: subscribe
  retries: 5
  delay: 5
  when: subscription_use_username == False

- debug:
    msg: "{{subscribe}}"

- name: Disable all repos
  shell: |
    subscription-manager repos --disable=*
  retries: 5
  delay: 5
  when: subscribe.changed

- name: Enable correct repos
  command: "subscription-manager repos --enable={{item}}"
  when: subscribe.changed
  retries: 5
  delay: 5
  with_items: "{{repos}}"

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Ensure that required packages are installed on target hosts
  yum:
    name: "{{item}}"
    state: latest
  retries: 5
  delay: 5
  with_items: "{{packages}}"
